### ISSUE TITLE
IDEA: Offer as Trait/Interface

### ISSUE THREAD

**Issue by ConnectGrid** [dealfonso/jsonobject#1]
Rather than a just pure JsonObject class, how about offering the functionality as a Trait and Interface? This would allow this library to be integrated into existing object hierarchies that already extend from a parent class.

**Comment by dealfonso** [comment]
hi, 

thank you for the idea. I need help seeing exactly how it could be done because this class may shadow other properties in the existing object. Could you please provide a use case to show how would it be used and the semantics? 

The main concern for me is semantics: e.g. if class A has a property "p", adding the trait may shadow that property and its semantics. An alternative may consist in not allowing shadowing properties and only adding new properties with JsonObject... but in this case, how may JsonObject be useful?

Taking care of shadowing properties is also important because of setters and getters. If you design an object which inherits from JsonObject from scratch, it is easier to make a better design.

An alternative is to have somehow a JsonProxy in which to define the properties and reflect them in an existing object... 

e.g. Having object B, with properties p1 and p2; being C a JsonObjectProxy to B will enable to make C->p1 = 4, which will use the validation of JsonObject, but will set B's p1 property instead of storing the value itself. Then, if getting the Object representation of C, it will get the values from B's properties.

What do you think about this?
